BROWN = (
    "Brown Ale - American",
    "Brown Ale - Belgian",
    "Brown Ale - English",
    "Brown Ale - Imperial / Double",
    "Brown Ale - Other",
)

BARLEYWINE = (
    "Barleywine - American",
    "Barleywine - English",
    "Barleywine - Other",
)

BELGIAN = (
    "Belgian Blonde",
    "Belgian Dubbel",
    "Belgian Quadrupel",
    "Belgian Strong Dark Ale",
    "Belgian Strong Golden Ale",
    "Belgian Tripel",
)

GRAPE = (
    "Grape Ale - Italian",
    "Grape Ale - Other",
)

STRONG = (
    "Strong Ale - American",
    "Strong Ale - English",
    "Strong Ale - Other",
)

BOCK = (
    "Bock - Doppelbock",
    "Bock - Eisbock (Traditional)",
    "Bock - Hell / Maibock / Lentebock",
    "Bock - Single / Traditional",
    "Bock - Weizenbock",
    "Bock - Weizendoppelbock",
)

PORTER = (
    "Porter - American",
    "Porter - Baltic",
    "Porter - Coffee",
    "Porter - English",
    "Porter - Imperial / Double",
    "Porter - Imperial / Double Baltic",
    "Porter - Imperial / Double Coffee",
    "Porter - Other",
)

PILSNER = (
    "Pilsner - Czech",
    "Pilsner - German",
    "Pilsner - Imperial / Double",
    "Pilsner - Other",
)

RED = (
    "Red Ale - American Amber / Red",
    "Red Ale - Imperial / Double",
    "Red Ale - Irish",
    "Red Ale - Other",
)

PALE = (
    "Pale Ale - American",
    "Pale Ale - Australian",
    "Pale Ale - Belgian",
    "Pale Ale - English",
    "Pale Ale - International",
    "Pale Ale - Milkshake",
    "Pale Ale - New England",
    "Pale Ale - New Zealand",
)

WHEAT = (
    "Wheat Beer - American Pale Wheat",
    "Wheat Beer - Other",
    "Wheat Beer - Wheat Wine",
    "Wheat Beer - Witbier",
    "Hefeweizen",
    "Hefeweizen Light / Leicht",
    "Kristallweizen",
)

LAGER = (
    "Lager - Amber",
    "Lager - American",
    "Lager - American Amber / Red",
    "Lager - American Light",
    "Lager - Dark",
    "Lager - Dortmunder / Export",
    "Lager - Euro Dark",
    "Lager - Euro Pale",
    "Lager - Helles",
    "Lager - IPL (India Pale Lager)",
    "Lager - Japanese Rice",
    "Lager - Munich Dunkel",
    "Lager - Pale",
    "Lager - Red",
    "Lager - Strong",
    "Lager - Vienna",
    "Lager - Winter",
)

SOUR = (
    "American Wild Ale",
    "Brett Beer",
    "Farmhouse Ale - Bière de Garde",
    "Farmhouse Ale - Bière de Mars",
    "Farmhouse Ale - Other",
    "Farmhouse Ale - Sahti",
    "Farmhouse Ale - Saison",
    "Grisette",
    "IPA - Sour",
    "Lambic - Faro",
    "Lambic - Framboise",
    "Lambic - Fruit",
    "Lambic - Gueuze",
    "Lambic - Kriek",
    "Lambic - Traditional",
    "Sour - Berliner Weisse",
    "Sour - Flanders Oud Bruin",
    "Sour - Flanders Red Ale",
    "Sour - Fruited",
    "Sour - Fruited Berliner Weisse",
    "Sour - Fruited Gose",
    "Sour - Gose",
    "Sour - Other",
    "Wild Ale - Other",
)

CIDER = (
    "Cider - Dry",
    "Cider - Graff",
    "Cider - Herbed / Spiced / Hopped",
    "Cider - Ice / Applewine",
    "Cider - Other Fruit",
    "Cider - Perry",
    "Cider - Rosé",
    "Cider - Sweet",
    "Cider - Traditional",
)

MEAD = (
    "Mead - Acerglyn / Maple Wine",
    "Mead - Braggot",
    "Mead - Cyser",
    "Mead - Melomel",
    "Mead - Metheglin",
    "Mead - Other",
    "Mead - Pyment",
    "Mead - Traditional",
)

IPA = (
    "IPA - American",
    "IPA - Belgian",
    "IPA - Black / Cascadian Dark Ale",
    "IPA - Brett",
    "IPA - Brut",
    "IPA - English",
    "IPA - Farmhouse",
    "IPA - Imperial / Double",
    "IPA - Imperial / Double Black",
    "IPA - Imperial / Double Milkshake",
    "IPA - Imperial / Double New England",
    "IPA - International",
    "IPA - Milkshake",
    "IPA - New England",
    "IPA - Quadruple",
    "IPA - Red",
    "IPA - Rye",
    "IPA - Session / India Session Ale",
    "IPA - Sour",
    "IPA - Triple",
    "IPA - Triple New England",
    "IPA - White",
)

STOUT = (
    "Stout - American",
    "Stout - Coffee",
    "Stout - English",
    "Stout - Foreign / Export",
    "Stout - Imperial / Double",
    "Stout - Imperial / Double Coffee",
    "Stout - Imperial / Double Milk",
    "Stout - Imperial / Double Oatmeal",
    "Stout - Imperial / Double Pastry",
    "Stout - Imperial / Double White",
    "Stout - Irish Dry",
    "Stout - Milk / Sweet",
    "Stout - Oatmeal",
    "Stout - Other",
    "Stout - Oyster",
    "Stout - Pastry",
    "Stout - Russian Imperial",
    "Stout - White",
)

OTHER = (
    "Adambier",
    "Altbier",
    "Australian Sparkling Ale",
    "Bière de Champagne / Bière Brut",
    "Black & Tan",
    "Blonde Ale",
    "Burton Ale",
    "California Common",
    "Chilli / Chile Beer",
    "Cream Ale",
    "Dampfbier",
    "Dark Ale",
    "Dunkelweizen",
    "English Bitter",
    "English Mild Ale",
    "Extra Special / Strong Bitter",
    "Festbier",
    "Freeze-Distilled Beer",
    "Fruit Beer",
    "Ginger Beer",
    "Gluten-Free",
    "Golden Ale",
    "Gruit / Ancient Herbed Ale",
    "Grätzer / Grodziskie",
    "Happoshu",
    "Hard Seltzer",
    "Historical Beer - Other",
    "Honey Beer",
    "Kellerbier / Zwickelbier",
    "Kentucky Common",
    "Kombucha",
    "Kvass",
    "Kölsch",
    "Lichtenhainer",
    "Malt Beer",
    "Malt Liquor ",
    "Mumme",
    "Märzen",
    "Non-Alcoholic Beer",
    "Old Ale",
    "Patersbier",
    "Pumpkin / Yam Beer",
    "Rauchbier",
    "Roggenbier",
    "Root Beer",
    "Rye Beer",
    "Rye Wine",
    "Schwarzbier",
    "Shandy / Radler",
    "Scotch Ale / Wee Heavy",
    "Scottish Ale",
    "Scottish Export Ale",
    "Smoked Beer",
    "Specialty Grain",
    "Spiced / Herbed Beer",
    "Steinbier",
    "Table Beer",
    "Traditional Ale",
    "Winter Ale",
    "Winter Warmer",
    "Zoigl",
)

STYLE_GROUPS = {
    "Barley Wine": BARLEYWINE,
    "Belgian": BELGIAN,
    "Bock": BOCK,
    "Brown": BROWN,
    "Cider": CIDER,
    "Grape": GRAPE,
    "IPA": IPA,
    "Lager": LAGER,
    "Mead": MEAD,
    "Other": OTHER,
    "Pale": PALE,
    "Pilsner": PILSNER,
    "Porter": PORTER,
    "Red": RED,
    "Sour": SOUR,
    "Stout": STOUT,
    "Strong": STRONG,
    "Wheat": WHEAT,
}

STYLES = (
    "Adambier",
    "Altbier",
    "American Wild Ale",
    "Australian Sparkling Ale",
    "Barleywine - American",
    "Barleywine - English",
    "Barleywine - Other",
    "Belgian Blonde",
    "Belgian Dubbel",
    "Belgian Quadrupel",
    "Belgian Strong Dark Ale",
    "Belgian Strong Golden Ale",
    "Belgian Tripel",
    "Bière de Champagne / Bière Brut",
    "Black & Tan",
    "Blonde Ale",
    "Bock - Doppelbock",
    "Bock - Eisbock (Traditional)",
    "Bock - Hell / Maibock / Lentebock",
    "Bock - Single / Traditional",
    "Bock - Weizenbock",
    "Bock - Weizendoppelbock",
    "Brett Beer",
    "Brown Ale - American",
    "Brown Ale - Belgian",
    "Brown Ale - English",
    "Brown Ale - Imperial / Double",
    "Brown Ale - Other",
    "Burton Ale",
    "California Common",
    "Chilli / Chile Beer",
    "Cider - Dry",
    "Cider - Graff",
    "Cider - Herbed / Spiced / Hopped",
    "Cider - Ice / Applewine",
    "Cider - Other Fruit",
    "Cider - Perry",
    "Cider - Rosé",
    "Cider - Sweet",
    "Cider - Traditional",
    "Cream Ale",
    "Dampfbier",
    "Dark Ale",
    "Dunkelweizen",
    "English Bitter",
    "English Mild Ale",
    "Extra Special / Strong Bitter",
    "Farmhouse Ale - Bière de Garde",
    "Farmhouse Ale - Bière de Mars",
    "Farmhouse Ale - Other",
    "Farmhouse Ale - Sahti",
    "Farmhouse Ale - Saison",
    "Festbier",
    "Freeze-Distilled Beer",
    "Fruit Beer",
    "Ginger Beer",
    "Gluten-Free",
    "Golden Ale",
    "Grape Ale - Italian",
    "Grape Ale - Other",
    "Grisette",
    "Gruit / Ancient Herbed Ale",
    "Grätzer / Grodziskie",
    "Happoshu",
    "Hard Seltzer",
    "Hefeweizen Light / Leicht",
    "Hefeweizen",
    "Historical Beer - Other",
    "Honey Beer",
    "IPA - American",
    "IPA - Belgian",
    "IPA - Black / Cascadian Dark Ale",
    "IPA - Brett",
    "IPA - Brut",
    "IPA - English",
    "IPA - Farmhouse",
    "IPA - Imperial / Double Black",
    "IPA - Imperial / Double Milkshake",
    "IPA - Imperial / Double New England",
    "IPA - Imperial / Double",
    "IPA - International",
    "IPA - Milkshake",
    "IPA - New England",
    "IPA - Quadruple",
    "IPA - Red",
    "IPA - Rye",
    "IPA - Session / India Session Ale",
    "IPA - Sour",
    "IPA - Sour",
    "IPA - Triple New England",
    "IPA - Triple",
    "IPA - White",
    "Kellerbier / Zwickelbier",
    "Kentucky Common",
    "Kombucha",
    "Kristallweizen",
    "Kvass",
    "Kölsch",
    "Lager - Amber",
    "Lager - American Amber / Red",
    "Lager - American Light",
    "Lager - American",
    "Lager - Dark",
    "Lager - Dortmunder / Export",
    "Lager - Euro Dark",
    "Lager - Euro Pale",
    "Lager - Helles",
    "Lager - IPL (India Pale Lager)",
    "Lager - Japanese Rice",
    "Lager - Munich Dunkel",
    "Lager - Pale",
    "Lager - Red",
    "Lager - Strong",
    "Lager - Vienna",
    "Lager - Winter",
    "Lambic - Faro",
    "Lambic - Framboise",
    "Lambic - Fruit",
    "Lambic - Gueuze",
    "Lambic - Kriek",
    "Lambic - Traditional",
    "Lichtenhainer",
    "Malt Beer",
    "Malt Liquor ",
    "Mead - Acerglyn / Maple Wine",
    "Mead - Braggot",
    "Mead - Cyser",
    "Mead - Melomel",
    "Mead - Metheglin",
    "Mead - Other",
    "Mead - Pyment",
    "Mead - Traditional",
    "Mumme",
    "Märzen",
    "Non-Alcoholic Beer",
    "Old Ale",
    "Pale Ale - American",
    "Pale Ale - Australian",
    "Pale Ale - Belgian",
    "Pale Ale - English",
    "Pale Ale - International",
    "Pale Ale - Milkshake",
    "Pale Ale - New England",
    "Pale Ale - New Zealand",
    "Patersbier",
    "Pilsner - Czech",
    "Pilsner - German",
    "Pilsner - Imperial / Double",
    "Pilsner - Other",
    "Porter - American",
    "Porter - Baltic",
    "Porter - Coffee",
    "Porter - English",
    "Porter - Imperial / Double Baltic",
    "Porter - Imperial / Double Coffee",
    "Porter - Imperial / Double",
    "Porter - Other",
    "Pumpkin / Yam Beer",
    "Rauchbier",
    "Red Ale - American Amber / Red",
    "Red Ale - Imperial / Double",
    "Red Ale - Irish",
    "Red Ale - Other",
    "Roggenbier",
    "Root Beer",
    "Rye Beer",
    "Rye Wine",
    "Schwarzbier",
    "Scotch Ale / Wee Heavy",
    "Scottish Ale",
    "Scottish Export Ale",
    "Shandy / Radler",
    "Smoked Beer",
    "Sour - Berliner Weisse",
    "Sour - Flanders Oud Bruin",
    "Sour - Flanders Red Ale",
    "Sour - Fruited Berliner Weisse",
    "Sour - Fruited Gose",
    "Sour - Fruited",
    "Sour - Gose",
    "Sour - Other",
    "Specialty Grain",
    "Spiced / Herbed Beer",
    "Steinbier",
    "Stout - American",
    "Stout - Coffee",
    "Stout - English",
    "Stout - Foreign / Export",
    "Stout - Imperial / Double Coffee",
    "Stout - Imperial / Double Milk",
    "Stout - Imperial / Double Oatmeal",
    "Stout - Imperial / Double Pastry",
    "Stout - Imperial / Double White",
    "Stout - Imperial / Double",
    "Stout - Irish Dry",
    "Stout - Milk / Sweet",
    "Stout - Oatmeal",
    "Stout - Other",
    "Stout - Oyster",
    "Stout - Pastry",
    "Stout - Russian Imperial",
    "Stout - White",
    "Strong Ale - American",
    "Strong Ale - English",
    "Strong Ale - Other",
    "Table Beer",
    "Traditional Ale",
    "Wheat Beer - American Pale Wheat",
    "Wheat Beer - Other",
    "Wheat Beer - Wheat Wine",
    "Wheat Beer - Witbier",
    "Wild Ale - Other",
    "Winter Ale",
    "Winter Warmer",
    "Zoigl",
)


def get_styles_by_ids(ids):
    return [STYLES[i] for i in ids]
