"""Add UntappdCache table

Revision ID: 3e10ea479777
Revises:
Create Date: 2025-08-16 17:36:58.631641

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e10ea479777"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "untappd_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("beer_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["beer_id"],
            ["beers.beer_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_untappd_cache_expires_at"), "untappd_cache", ["expires_at"], unique=False)
    op.create_index(op.f("ix_untappd_cache_query"), "untappd_cache", ["query"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_untappd_cache_query"), table_name="untappd_cache")
    op.drop_index(op.f("ix_untappd_cache_expires_at"), table_name="untappd_cache")
    op.drop_table("untappd_cache")
    # ### end Alembic commands ###
