"""Add DeepLCache table

Revision ID: a259d8878185
Revises: 3e10ea479777
Create Date: 2025-08-16 20:43:28.360654

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a259d8878185"
down_revision: str | Sequence[str] | None = "3e10ea479777"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deepl_cache",
        sa.Column("source_text", sa.String(), nullable=False),
        sa.Column("translated_text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("source_text"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deepl_cache")
    # ### end Alembic commands ###
