"""Add brewery fields and Beer-Brewery relationship

Revision ID: adf73c371c58
Revises: a259d8878185
Create Date: 2025-08-16 22:34:37.610960

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adf73c371c58"
down_revision: str | Sequence[str] | None = "a259d8878185"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns to breweries table first
    op.add_column("breweries", sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("breweries", sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Add columns to beers table without batch mode first
    op.add_column("beers", sa.Column("brewery_id", sa.Integer(), nullable=True))
    op.add_column("beers", sa.Column("weighted_rating", sa.Float(), nullable=True))
    op.add_column("beers", sa.Column("rating_count", sa.Integer(), nullable=True))
    op.add_column("beers", sa.Column("total_user_count", sa.Integer(), nullable=True))

    # Now add the foreign key constraint using batch mode
    with op.batch_alter_table("beers", schema=None) as batch_op:
        batch_op.create_foreign_key("fk_beers_brewery_id", "breweries", ["brewery_id"], ["brewery_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("breweries", "state")
    op.drop_column("breweries", "city")

    # Use batch mode for SQLite to handle foreign key constraint
    with op.batch_alter_table("beers", schema=None) as batch_op:
        batch_op.drop_constraint("fk_beers_brewery_id", type_="foreignkey")
        batch_op.drop_column("total_user_count")
        batch_op.drop_column("rating_count")
        batch_op.drop_column("weighted_rating")
        batch_op.drop_column("brewery_id")
    # ### end Alembic commands ###
